sonar.projectKey=omnicharge
sonar.projectName=OmniCharge
sonar.sourceEncoding=UTF-8

sonar.sources=PaymentService/src/main/java,RechargeProcessing/src/main/java,UserManagement/src/main/java,OperatorPlanManagement/src/main/java,notification-service/src/main/java
sonar.tests=PaymentService/src/test/java,RechargeProcessing/src/test/java,UserManagement/src/test/java,OperatorPlanManagement/src/test/java,notification-service/src/test/java

sonar.java.binaries=PaymentService/target/classes,RechargeProcessing/target/classes,UserManagement/target/classes,OperatorPlanManagement/target/classes,notification-service/target/classes
sonar.junit.reportPaths=PaymentService/target/surefire-reports,RechargeProcessing/target/surefire-reports,UserManagement/target/surefire-reports,OperatorPlanManagement/target/surefire-reports,notification-service/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=PaymentService/target/site/jacoco/jacoco.xml,RechargeProcessing/target/site/jacoco/jacoco.xml,UserManagement/target/site/jacoco/jacoco.xml,OperatorPlanManagement/target/site/jacoco/jacoco.xml,notification-service/target/site/jacoco/jacoco.xml

sonar.exclusions=**/target/**,**/bin/**,**/logs/**
sonar.coverage.exclusions=**/*Application.java,**/configuration/**,**/config/**,**/controller/**,**/dto/**,**/entity/**,**/enums/**,**/exception/**,**/filter/**,**/repository/**,**/feignClient/**,**/consumer/**,**/mapper/**,**/service/I*.java
